apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
  labels:
    app: first-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-deployment
  template:
    metadata:
      labels:
        app: first-deployment
    spec:
      containers:
        - name: first-deployment
          image: pqr:latest
          imagePullPolicy: IfNotPresent
